### ISSUE TITLE
Baseten instructions

### ISSUE THREAD

**Issue by kholbekj** [hmartiro/riffusion-inference#14]
Hey, sorry but I'm failing to understand how to setup baseten for use with riffusion. Is it possible to add some steps?

**Comment by erprogs** [comment]
this worked for me

create `.env.local` file in the inference folder


add `RIFFUSION_FLASK_URL=http://127.0.0.1:3013/run_inference/` to the file.

**Comment by kholbekj** [comment]
Issue was definitely on the wrong repo. The point here is to use baseten and not this repo :D
